### ISSUE TITLE
Make this build on 32-bit systems

### ISSUE THREAD

**Issue by andrewthad** [haskell-primitive/primitive-unaligned#1]
This is not difficult to do. It's just a little difficult to confirm that it works since I'll need to spin up a container or a VM.

**Comment by chessai** [comment]
you can do this with nix, very easily.

put the following in a shell.nix:

```nix
with import <nixpkgs> { system = "i686-linux"; };
stdenv.mkDerivation {
  name = "i686-shell-for-haskell";
  buildInputs = [
    (pkgsi686Linux.haskell.packages.ghc865.ghcWithPackages (pkgs: with pkgs; [ base ]))
  ];
}
```

then, in a haskell file:

```haskell
{-# language ScopedTypeVariables #-}

module Main where

import Foreign.Storable

main :: IO ()
main = print $ sizeOf (undefined :: Int)
```

now:

```
nix-shell --run 'ghc main.hs -o main && ./main'
```

It will print 4, whereas the following will print 8:

```
nix-shell -p haskell.compiler.ghc865 --run 'ghc main.hs -o main && ./main && rm main'
```

**Comment by andrewthad** [comment]
Awesome, thanks. I've added a `shell-i686.nix` to the project in efe44219c325d14d431aa8a79b1b30c43018c758, where I was also able to confirm that the operations on `Int64` and `Word64` compile and behave correctly in a 32-bit environment.
