### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by wwwater** [haskell-primitive/primitive-unaligned#13]
Hi! 
First, I want to thank you for maintaining this library, it's used as direct and indirect dependency in many other libraries and is an important part of the Haskell world.
Also, I wanted to comment that the recent bump for the `base` version (https://github.com/haskell-primitive/primitive-unaligned/commit/f2b51d3a0f6d558383af5732a27a62850aca2d41) should have been released as a new version in this dependency. 
This is quite a big change, and alters an already released version (0.1.1.2) in a significant way (basically requiring GHC >=9.4 to compile), thus I think it deserves a version bump on part of this library.

**Comment by andrewthad** [comment]
Thanks for bringing this up. I've just now rolled back that metadata revision on hackage. I had thought, based on a different open issue, that this library was no longer building with GHC 9.0 at all, but it looks like it's just on a particular architecture.
