### ISSUE TITLE
cabal check failures

### ISSUE THREAD

**Issue by chessai** [haskell-primitive/primitive-unaligned#2]
there are numerous, and cause the travis builds to exit with exitcode 1:

```
Warning: These warnings may cause trouble when distributing the package:
Warning: When distributing packages it is encouraged to specify source control
information in the .cabal file using one or more 'source-repository' sections.
See the Cabal user guide for details.
Warning: No 'description' field.
Warning: 'ghc-options: -O2' is rarely needed. Check that it is giving a real
benefit and not just imposing longer compile times on your users.
Warning: The following errors will cause portability problems on other
environments:
Warning: Unknown architecture name 'i686'
Warning: Hackage would reject this package.
```

**Comment by chessai** [comment]
obviously the failure is because of the 'i686' thing, but i think this is a failure of cabal to recognise 'i686', and not this package's fault.

**Comment by chessai** [comment]
(hopefully) temporary workaround in e4bd159, by removing the i686 branch in the architecture check

**Comment by andrewthad** [comment]
Resolved by https://github.com/haskell-primitive/primitive-unaligned/pull/3. Uncommon processors will still fail, but I'll wait until their users roll in with complaints before trying to address this. (For example, in a cabal file, it doesn't appear to be possible to distinguish between 32-bit SPARC and 64-bit, so I don't know what to do here.)
