### ISSUE TITLE
unaligned access on armhf with arm64 kernel

### ISSUE THREAD

**Issue by LocutusOfBorg** [haskell-primitive/primitive-unaligned#9]
Hello, looks like that there is some unaligned access with an arm64 kernel and the armhf package

```
Building library for primitive-unaligned-0.1.1.1..
[1 of 2] Compiling Data.Primitive.Unaligned.Mach ( src-32/Data/Primitive/Unaligned/Mach.hs, dist-ghc/build/Data/Primitive/Unaligned/Mach.o )
[2 of 2] Compiling Data.Primitive.ByteArray.Unaligned ( src/Data/Primitive/ByteArray/Unaligned.hs, dist-ghc/build/Data/Primitive/ByteArray/Unaligned.o )
[1 of 2] Compiling Data.Primitive.Unaligned.Mach ( src-32/Data/Primitive/Unaligned/Mach.hs, dist-ghc/build/Data/Primitive/Unaligned/Mach.p_o )
[2 of 2] Compiling Data.Primitive.ByteArray.Unaligned ( src/Data/Primitive/ByteArray/Unaligned.hs, dist-ghc/build/Data/Primitive/ByteArray/Unaligned.p_o )
Preprocessing test suite 'unit' for primitive-unaligned-0.1.1.1..
Building test suite 'unit' for primitive-unaligned-0.1.1.1..
[1 of 1] Compiling Main             ( test/Unit.hs, dist-ghc/build/unit/unit-tmp/Main.o )
Linking dist-ghc/build/unit/unit ...
touch build-ghc-stamp
. /usr/share/haskell-devscripts/Dh_Haskell.sh && \
check_recipe
Running debian/hlibrary.setup test --builddir=dist-ghc --show-details=direct
Running 1 test suites...
Test suite unit: RUNNING...
Test suite unit: FAIL
Test suite logged to: dist-ghc/test/primitive-unaligned-0.1.1.1-unit.log
0 of 1 test suites (0 of 1 test cases) passed.
make: *** [/usr/share/cdbs/1/class/hlibrary.mk:154: check-ghc-stamp] Error 1
dpkg-buildpackage: error: debian/rules build-arch subprocess returned exit status 2
```
see, e.g. this erorr: https://launchpadlibrarian.net/488162800/buildlog_ubuntu-groovy-armhf.haskell-primitive-unaligned_0.1.1.1-1ubuntu1_BUILDING.txt.gz

**Comment by andrewthad** [comment]
Ah, an ARM user has finally tried to build this library. This library doesn't actually do the right thing on ARM. Primops like `readWord8ArrayAsWord64#` crash on ARM, so I need to shim those out by manually composing the results of eight read instructions. This is not difficult, just a little tedious. I'll try to address this tomorrow.

**Comment by LocutusOfBorg** [comment]
interesting, because testsuite passes on
armel
armhf
arm64

with no errors at all.
the only problem we get is armhf with an arm64 kernel, because of unaligned accesses.

So I presume your testsuite is not trying to run that code?

**Comment by andrewthad** [comment]
The tests are run unconditionally on any architecture. I'm not terribly knowledgeable about how unaligned memory access actually gets handled on ARM. I had always assumed that a process doing this would be killed. But maybe the access is trapped and emulated by the operating system. I don't actually know. If you know the answer to that, that could help.

One other possibility is that these stanzas in the cabal file are doing the wrong thing:

```
  if arch(aarch64) || arch(alpha) || arch(ia64) || arch(ppc64) || arch(powerpc64) || arch(powerpc64le) || arch(riscv64) || arch(s390x) || arch(sparc64) || arch(x86_64) || arch(mips64el)
    hs-source-dirs: src-64
  if arch(arm) || arch(hppa) || arch(hppa1_1) || arch(i386) || arch(m68k) || arch(mips) || arch(mipseb) || arch(mipsel) || arch(nios2) || arch(powerpc) || arch(riscv32) || arch(rs6000) || arch(s390) || arch(sh4) || arch(sparc) || arch(vax)
    hs-source-dirs: src-32
```

If `src-32` gets used on a 64-bit OS, that would cause a crash.

Also, the build log mentions:

    Test suite logged to: dist-ghc/test/primitive-unaligned-0.1.1.1-unit.log

But the contents of `dist-ghc/test/primitive-unaligned-0.1.1.1-unit.log` are not included. If you are able to get the contents of that file, that may help diagnose this problem.

**Comment by LocutusOfBorg** [comment]
Running cat dist-ghc/test/primitive-unaligned-0.1.1.2-unit.log dist-ghc/test/primitive-unaligned-0.1.1.2.log
Test suite unit: RUNNING...
Test suite unit: FAIL
Test suite logged to: dist-ghc/test/primitive-unaligned-0.1.1.2-unit.log
PackageLog {package = PackageIdentifier {pkgName = PackageName "primitive-unaligned", pkgVersion = mkVersion [0,1,1,2]}, compiler = CompilerId GHC (mkVersion [9,0,2]), platform = Platform Arm Linux, testSuites = [TestSuiteLog {testSuiteName = UnqualComponentName "unit", testLogs = TestLog {testName = "unit", testOptionsReturned = [], testResult = Fail "exit code: -7"}, logFile = "dist-ghc/test/primitive-unaligned-0.1.1.2-unit.log"}]}
touch check-ghc-stamp
perl -d:Confess -MDebian::Debhelper::Buildsystem::Haskell::Recipes=/.*/ \

**Comment by LocutusOfBorg** [comment]
this is the log

**Comment by LocutusOfBorg** [comment]
and trying to use src-64 on armhf fails with:
```
libghc-primitive-unaligned-prof
libghc-primitive-unaligned-doc
Preprocessing library for primitive-unaligned-0.1.1.2..
Building library for primitive-unaligned-0.1.1.2..
[1 of 2] Compiling Data.Primitive.Unaligned.Mach ( src-64/Data/Primitive/Unaligned/Mach.hs, dist-ghc/build/Data/Primitive/Unaligned/Mach.o, dist-ghc/build/Data/Primitive/Unaligned/Mach.dyn_o )

src-64/Data/Primitive/Unaligned/Mach.hs:25:6: error:
    • Couldn't match expected type ‘E.Word64#’
                  with actual type ‘E.Word#’
    • In the first argument of ‘W64#’, namely
        ‘((E.indexWord8ArrayAsWord# a i))’
      In the expression: W64# ((E.indexWord8ArrayAsWord# a i))
      In an equation for ‘indexUnalignedWord64Array#’:
          indexUnalignedWord64Array# a i
            = W64# ((E.indexWord8ArrayAsWord# a i))
   |
25 |     (E.indexWord8ArrayAsWord# a i))
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src-64/Data/Primitive/Unaligned/Mach.hs:33:6: error:
    • Couldn't match expected type ‘E.Int64#’ with actual type ‘Int#’
    • In the first argument of ‘I64#’, namely
        ‘((E.indexWord8ArrayAsInt# a i))’
      In the expression: I64# ((E.indexWord8ArrayAsInt# a i))
      In an equation for ‘indexUnalignedInt64Array#’:
          indexUnalignedInt64Array# a i
            = I64# ((E.indexWord8ArrayAsInt# a i))
   |
33 |     (E.indexWord8ArrayAsInt# a i))
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^

src-64/Data/Primitive/Unaligned/Mach.hs:46:9: error:
    • Couldn't match expected type ‘E.Word64#’
                  with actual type ‘E.Word#’
    • In the first argument of ‘W64#’, namely ‘(r)’
      In the expression: W64# (r)
      In the expression: (# s1, W64# (r) #)
   |
46 |         r)
   |         ^

src-64/Data/Primitive/Unaligned/Mach.hs:60:9: error:
    • Couldn't match expected type ‘E.Int64#’ with actual type ‘Int#’
    • In the first argument of ‘I64#’, namely ‘(r)’
      In the expression: I64# (r)
      In the expression: (# s1, I64# (r) #)
   |
60 |         r) #)
   |         ^

src-64/Data/Primitive/Unaligned/Mach.hs:73:5: error:
    • Couldn't match expected type ‘E.Word#’
                  with actual type ‘E.Word64#’
    • In the third argument of ‘E.writeWord8ArrayAsWord#’, namely ‘(w)’
      In the expression: E.writeWord8ArrayAsWord# a i (w)
      In an equation for ‘writeUnalignedWord64Array#’:
          writeUnalignedWord64Array# a i (W64# w)
            = E.writeWord8ArrayAsWord# a i (w)
   |
73 |     w)
   |     ^

src-64/Data/Primitive/Unaligned/Mach.hs:86:5: error:
    • Couldn't match expected type ‘Int#’ with actual type ‘E.Int64#’
    • In the third argument of ‘E.writeWord8ArrayAsInt#’, namely ‘(w)’
      In the expression: E.writeWord8ArrayAsInt# a i (w)
      In an equation for ‘writeUnalignedInt64Array#’:
          writeUnalignedInt64Array# a i (I64# w)
            = E.writeWord8ArrayAsInt# a i (w)
   |
86 |     w)
   |     ^
-e: error: debian/hlibrary.setup build --builddir=dist-ghc returned exit code 1
 at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 880.
	Debian::Debhelper::Dh_Lib::error("debian/hlibrary.setup build --builddir=dist-ghc returned exit"...) called at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 610
	Debian::Debhelper::Dh_Lib::error_exitcode("debian/hlibrary.setup build --builddir=dist-ghc") called at /usr/share/perl5/Debian/Debhelper/Dh_Lib.pm line 473
	Debian::Debhelper::Dh_Lib::doit("debian/hlibrary.setup", "build", "--builddir=dist-ghc") called at /usr/share/perl5/Debian/Debhelper/Buildsystem/Haskell/Recipes.pm line 650
	Debian::Debhelper::Buildsystem::Haskell::Recipes::build_recipe() called at -e line 1
make: *** [/usr/share/cdbs/1/class/hlibrary.mk:160: build-ghc-stamp] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary-arch subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2023-10-16T14:41:10Z

Finished
--------
```

**Comment by andrewthad** [comment]
Which version of GHC was that with?

**Comment by LocutusOfBorg** [comment]
9.0.2. We are moving to 9.4.6 and 9.4.7 as soon as Ubuntu opens for development again

**Comment by andrewthad** [comment]
On hackage, I've bumped the lower bound on base to require GHC 9.4. The current version of this library is not expected to work with older GHCs.

**Comment by andrewthad** [comment]
I've rolled back this metadata revision. I thought that this was failure to build on GHC 9.0 everywhere, but it looks like it's just on `armhf`.

**Comment by andrewthad** [comment]
I just looked into this a little more. armhf is a 32-bit architecture, so using src-64 definitely will not work. Your logs from running the test suite are missing information. Instead of running `cabal test`, run `cabal build primitive-unaligned:unit`, and then run the test suite by hand (the build command will print out the test suite's location, for me it's at `/home/amartin/Data/Development/primitive-unaligned/dist-newstyle/build/x86_64-linux/ghc-9.4.7/primitive-unaligned-0.1.1.2/t/unit/build/unit/unit` but for you it will be somewhere else). After this, run `echo "$?"` to get the exit status. Post the output of the test suite itself and the exit status.

**Comment by LocutusOfBorg** [comment]
https://launchpadlibrarian.net/696427707/buildlog_ubuntu-noble-armhf.haskell-primitive-unaligned_0.1.1.2-2ubuntu4_BUILDING.txt.gz

Looks like it doesn't fail anymore with newer ghc!
